version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: moderation_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moderation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: moderation_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/moderation_db
      SECRET_KEY: your-secret-key-change-in-production
      ML_MODEL_CACHE_DIR: /app/model_cache
      LOG_LEVEL: INFO
      # LLM Configuration (Optional - uncomment and set to use)
      # LLM_PROVIDER: ${LLM_PROVIDER:-}
      # LLM_API_KEY: ${LLM_API_KEY:-}
      # LLM_MODEL: ${LLM_MODEL:-}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - model_cache:/app/model_cache
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: moderation_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  model_cache:
